Repository DharshiBalasubramaniyam/ice-cream-parlour-website, pull requests merged in 2024-10, with the labels that each got.

#32 Add bottom to top button
  images/icecream-cone.png
  index.html
  script/nav.js
  styles/styles.css
Labels: question, gssoc-ext, level 1, hacktoberfest-accepted

#52 issue #25 closes (devxMani)
  index.html
Labels: question, gssoc-ext, level 1, hacktoberfest-accepted

#78 Created a new webpage for Island Wide Delivery
  delivery-address.html
  html/delivery-address.html
  index.html
  styles/styles.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#108 Added more FAQ questions
  index.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#123 Add Login Page and Link it to Home Page
  index.html
  sign-in.html
  styles/sign.in.css
Labels: question, gssoc-ext, level 2, hacktoberfest-accepted

#118 Increased Logo Size
  index.html
  styles/styles.css
Labels: question, gssoc-ext, level 1, hacktoberfest-accepted

#122 [BUG] Contact Form Fixed
  styles/styles.css
Labels: question, gssoc-ext, level1, hacktoberfest-accepted

#144 Added Pre-loader #145
  .vscode/settings.json
  delivery.html
  dine-in.html
  index.html
  styles/dine.css
  styles/styles.css
Labels: question, gssoc-ext, level1, hacktoberfest-accepted

#150 Added Progress Bar and Scroll-to-Top Button
  index.html
  script/topscrollindicator.js
  styles/styles.css
  styles/topscrollindicator.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#277 login signup responsive
  login.html
  signup.html
  styles/style1.css
  styles/style2.css
Labels: gssoc-ext, level2, hacktoberfest-accepted

#275 Improved date picker in form
  catering.html
  script/catering.js
Labels: question, gssoc-ext, hacktoberfest-accepted

#202 updated readme.md and also create Contribution.md file with guidelines
  CONTRIBUTION.md
  README.md
Labels: gssoc-ext, level1, hacktoberfest-accepted

#184 Added Template & fixed the preloader time
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ISSUE_TEMPLATE/documentation.yaml
  .github/workflows/ISSUE_TEMPLATE/issue_request.yaml
  index.html
  styles/styles.css
Labels: gssoc-ext, level2, hacktoberfest-accepted

#357 Pop up for discount added
  images/popupice.jpg
  index.html
  script/popup.js
  styles/popup.css
Labels: gssoc-ext, level3, hacktoberfest-accepted

#378 social links updated
  index.html
Labels: question, gssoc-ext, hacktoberfest-accepted

#153 Adding a star rating system to each product (issue #87)
  script/product_database.js
  script/products.js
  styles/styles.css
Labels: question, gssoc-ext, level1, hacktoberfest-accepted

#192 Main image is changed now (no water mark and improved image)
  index.html
  mainimg.png
  styles/styles.css
Labels: question, gssoc-ext, level1, hacktoberfest-accepted

#209 product hover #200
  styles/styles.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#206 solved issue #172
  script/form.js
Labels: question, gssoc-ext, level1, hacktoberfest-accepted

#228 Update font style of home page
  styles/styles.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#289 Add account/sign in options in box
  styles/style1.css
Labels: question, gssoc-ext, hacktoberfest-accepted

#371 Feature/image round issue #362
  styles/styles.css
Labels: question, gssoc-ext, hacktoberfest-accepted

#380 #284 Issue [Solved]:- Succesfully Modified Javascript of Navbar
  script/nav.js
Labels: question, gssoc-ext, hacktoberfest-accepted

#405 resolve the submit and reset btn
  delivery.html
  styles/form.css
Labels: question, gssoc-ext, hacktoberfest-accepted

#436 Changed the current loader style #416fixed
  images/flavour-icon.png
  images/friendly-icon.png
  images/hygiene-icon.png
  images/quality-icon.png
  index.html
  styles/styles.css
Labels: question, gssoc-ext, hacktoberfest-accepted

#451 Added password meter
  signup.html
Labels: gssoc-ext, level2, hacktoberfest-accepted

#498 Added a dark theme toggle to home page.
  index.html
  script/dark_theme.js
  script/reviews.js
  styles/dark_theme.css
  styles/styles.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#501 Adding scrolling animation. #440
  index.html
  styles/styles.css
Labels: question, gssoc-ext, hacktoberfest-accepted

#433 text alignment to center in production section
  script/products.js
  styles/styles.css
Labels: question, gssoc-ext, hacktoberfest-accepted

#456 khurshed07
  styles/styles.css
Labels: question, gssoc-ext, hacktoberfest-accepted

#507 Login and Signup page ui updated
  images/social-icons/Facebook.svg
  login.html
  signup.html
  styles/style2.css
Labels: question, gssoc-ext, hacktoberfest-accepted

#542 Update styles.css
  styles/styles.css
Labels: gssoc-ext, level2, hacktoberfest-accepted

#564 Update gallary.html - Deleted "Order Online" button.
  gallary.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#518 UI fix
  index.html
  styles/styles.css
Labels: question, gssoc-ext, hacktoberfest-accepted

#540 ✨#issue #483 has been solved ✨
  .vscode/settings.json
  index.html
  script/reviews.js
  script/script.js
Labels: question, gssoc-ext, hacktoberfest-accepted

#519 Add Hover Effects to Why IcyCo? Section
  styles/styles.css
Labels: question, gssoc-ext, hacktoberfest-accepted

#530 deleted repeated restaurants
  dine-in.html
  privacy.html
  styles/privacy.css
Labels: question, gssoc-ext, hacktoberfest-accepted

#662 Add Search Button on Ice Cream Product Page #474
  products.html
  script/products.js
Labels: question, gssoc-ext, hacktoberfest-accepted

#654 Make copyright year dynamic
  blogs.html
  catering.html
  delivery.html
  dine-in.html
  faq.html
  gallary.html
  index.html
  privacy.html
  products.html
  script/nav.js
  subscriptions.html
Labels: question, gssoc-ext, hacktoberfest-accepted

#742 Footer Links Updation
  blogs.html
  catering.html
  delivery.html
  dine-in.html
  faq.html
  gallary.html
  index.html
  privacy.html
  products.html
  subscriptions.html
  terms&condition.html
Labels: question, gssoc-ext, hacktoberfest-accepted

#710 Fixed Cart not working in gallery and blog section
  blogs.html
  gallary.html
Labels: question, gssoc-ext, hacktoberfest-accepted

#714 changed the bg of login html and added css
  login.html
  styles/styles3.css
Labels: question, gssoc-ext, hacktoberfest-accepted

#688 enhance the logo and update the icons with some animation or hover effect
  index.html
  styles/styles.css
Labels: question, gssoc-ext, hacktoberfest-accepted

#735 Added wishlist icon, wishlist side bar toggle, wishlist button in cards.
  blogs.html
  catering.html
  delivery.html
  dine-in.html
  faq.html
  gallary.html
  index.html
  privacy.html
  products.html
  script/products.js
  script/wishlist.js
  styles/styles.css
  subscriptions.html
Labels: question, gssoc-ext, hacktoberfest-accepted

#796 Top scroll bar indicator Added in every html pages.
  blogs.html
  catering.html
  contributor.html
  delivery.html
  dine-in.html
  faq.html
  gallary.html
  index.html
  login.html
  privacy.html
  products.html
  script/topscrollindicator.js
  signup.html
  styles/topscrollindicator.css
  subscriptions.html
Labels: question, gssoc-ext, hacktoberfest-accepted

#772 Fixed #223: Integrate Chatbot named FrostyGuide
  index.html
  script/script.js
  styles/styles.css
Labels: question, gssoc-ext, hacktoberfest-accepted

#736 Added functionality to wishlist button
  delivery.html
  products.html
  script/products.js
  styles/styles.css
Labels: question, gssoc-ext, hacktoberfest-accepted

#779 icons added
  index.html
Labels: question, gssoc-ext, hacktoberfest-accepted

#820 add the same UI for privacy and terms and conditions and also added cursor
  privacy.html
  styles/privacy.css
  styles/terms.css
Labels: question, gssoc-ext, hacktoberfest-accepted

#805 Cart UI modification
  script/products.js
  styles/products.css
Labels: question, gssoc-ext, hacktoberfest-accepted

#949 Loader issue, issue Number #943 is solved
  styles/mediaQueries.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#950 footer icon fixed
  index.html
Labels: gssoc-ext, level1, hacktoberfest-accepted

#974 Added empty cart sidebar
  blogs.html
  catering.html
  contributor.html
  delivery.html
  dine-in.html
  faq.html
  gallary.html
  images/empty-cart.png
  index.html
  privacy.html
  products.html
  styles/styles.css
  subscriptions.html
  terms&condition.html
Labels: question, gssoc-ext, level2, hacktoberfest-accepted
